- name: download docker
  get_url:
    url: https://get.docker.com
    dest: /tmp/get-docker.sh
    mode: a+x
  become: yes
- name: install docker
  shell: creates=/usr/bin/docker /tmp/get-docker.sh
  become: yes
- name: add user to docker group
  user: name={{username}} groups=docker append=yes
  become: yes
- name: install docker-compose dependencies
  apt:
    name:
      - libffi-dev
      - libssl-dev
      - python3
      - python3-pip
  become: yes
- name: install docker-compose
  pip:
    name:
      - docker-compose
    executable: pip3
  become: yes