- name: install podman-compose dependencies
  dnf:
    name:
      - python3
      - python3-pip
  become: yes
- name: install podman
  dnf:
    name:
      - podman
  become: yes
- name: install podman-compose
  pip:
    name:
      - podman-compose
    executable: pip3
  become: yes
